version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_authentication
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: api_authentication_db
    ports:
      - 5432:5432
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=api_aplication